### ISSUE TITLE
4.2 branch kind, channel, body = msg TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by jammed343** [thefab/tornadis#19]
I would like to use the 4.2 branch, actually would like to go straight of the master tornado branch. However, when using just the 4.2 branch here and tornado 4.2 thats just  installed from the requirements and I'm getting an error on pubsub message, which works fine on 4.1.

kind, channel, body = msg
TypeError: 'NoneType' object is not iterable

Traceback (most recent call last):
  File ".../python2.7/site-packages/tornado/ioloop.py", line 592, in _run_callback
    ret = callback()
  File ".../python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(_args, *_kwargs)
  File ".../python2.7/site-packages/tornado/ioloop.py", line 598, in <lambda>
    self.add_future(ret, lambda f: f.result())
  File ".../python2.7/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File ".../python2.7/site-packages/tornado/gen.py", line 879, in run
    yielded = self.gen.send(value)
  File "project.py", line 127, in watch_redis
    self.on_pubsub(msg)
  File "project.py", line 131, in on_pubsub
    kind, channel, body = msg
TypeError: 'NoneType' object is not iterable

Any ideas on why pubsub messages have just become `None` so we can get this working on 4.2, and I'll also try on latest tornado straight from master.

**Comment by thefab** [comment]
I will have a look

**Comment by thefab** [comment]
confirmed

**Comment by thefab** [comment]
I close this (thanks)

BTW, I'm going to merge this branch into master soon (and keep a "tornado < 4.2" branch)
