### ISSUE TITLE
why can't connect redis db ???  

### ISSUE THREAD

**Issue by gzg365** [thefab/tornadis#46]
tornadis 0.8.0
tornado 5.0.1
python 3.6.5
------------------------------------------------------------------------------------------------------------------
class MyVerification(RequestHandler):
    @tornado.gen.coroutine
    def get(self):
        self.redisdb = tornadis.Client(db=1)
        result = yield self.redisdb.call("SET", self.myId, myValue)
        self.write(result)
------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/python3/lib/python3.6/site-packages/tornado/web.py", line 1543, in _execute
    result = yield result
  File "/app/python3/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/app/python3/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/app/tornadoWeb/com/verification.py", line 30, in get
    result = yield self.redisdb.call("SET", self.myId, myValue)
  File "/app/python3/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/app/python3/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/app/python3/lib/python3.6/site-packages/tornadis/client.py", line 212, in _call_with_autoconnect
    yield self.connect()
  File "/app/python3/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/app/python3/lib/python3.6/site-packages/tornado/gen.py", line 315, in wrapper
    yielded = next(result)
  File "/app/python3/lib/python3.6/site-packages/tornadis/client.py", line 101, in connect
    self.__connection = Connection(cb1, cb2, **kwargs)
  File "/app/python3/lib/python3.6/site-packages/tornadis/connection.py", line 87, in __init__
    self._ioloop)
TypeError: __init__() takes 3 positional arguments but 4 were given

**Comment by thefab** [comment]
just fixed in master (API break in tornado 5)

**Comment by gzg365** [comment]
@thefab 👍❤
