### ISSUE TITLE
Tornado 6 not supported by current version (0.8.1)

### ISSUE THREAD

**Issue by alff0x1f** [thefab/tornadis#50]
I saw in requirements tornado>=4.2,<6.0, but maybe this issue will be usefull for someone.

Tornado drop some methods:

> #### tornado.gen
>
> Some older portions of this module have been removed. This includes engine, YieldPoint, Callback, Wait, WaitAll, MultiYieldPoint, and Task.

[Release notes Tornado 6.0](https://www.tornadoweb.org/en/stable/releases/v6.0.0.html)

### My system:

python 3.8.0
tornadis 0.8.1
tornado: 6.0.3

And after update tornado I get this error:

```
ERROR:root:Traceback (most recent call last):
  File "/src/venv/lib/python3.8/site-packages/tornado/web.py", line 1699, in _execute
    result = await result
  File "/src/venv/lib/python3.8/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/src/handlers/auth.py", line 284, in post
    yield self.redis.call("DEL", auth_token)
  File "/src/venv/lib/python3.8/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/src/venv/lib/python3.8/site-packages/tornado/gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "/src/venv/lib/python3.8/site-packages/tornadis/client.py", line 215, in _call_with_autoconnect
    res = yield self._call(*args, **kwargs)
  File "/src/venv/lib/python3.8/site-packages/tornadis/client.py", line 285, in _call
    return tornado.gen.Task(fn, *arguments, **kwargs)
AttributeError: module 'tornado.gen' has no attribute 'Task'
```

**Comment by wangwanyou** [comment]
Yes, I also encountered this problem.
